service: uf-tech-talk-test # Change this to be unique
provider:
  name: aws
  runtime: python2.7
  # profile: personal
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "*"
      Resource:
        - "*" # Don't do this, just for quick demo. Really, don't
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          cors: true
          path: hello
          method: get

package:
  excludeDevDependencies: True
  exclude:
    - venv/**
    - package.json
    - package-lock.json
    - README.md
    - build/**
    - node_modules/**
plugins:
  - serverless-s3-sync
resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}
        WebsiteConfiguration:
          IndexDocument: index.html
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: AssetsBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  ["", ["arn:aws:s3:::", { "Ref": "AssetsBucket" }, "/*"]]
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: test-table
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
custom:
  s3Sync:
    - bucketName: ${self:service}
      localDir: build
      acl: public-read # optional
